apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charity
  template:
    metadata:
      labels:
        app: charity
    spec:
      containers:
      - name: charity-pod
        image: <enter-your-container-registry>/charity:0.1
        env:
        - name: DATABASE_HOST
          value: <enter-your-host>
        - name: DATABASE_PORT
          value: "<enter-your-port>"
        - name: DATABASE_NAME
          value: charity
        - name: DATABASE_USERNAME
          value: <enter-your-username>
        - name: DATABASE_PASSWORD
          value: <enter-your-password>
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: media-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: media
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: media-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: <enter-your-host>
    http:
      paths:
      - backend:
          serviceName: media-svc
          servicePort: 80
        path: /media